title: XMPC

author:
  name: XhuOffice
  email: xhuoffice@xhuoffice.tk
description: "Xhu Minecraft: Java Edition PvP Competition"
show_excerpts: false 

header_pages:
 
remote_theme: XhuOffice/minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
